all:
	@cd non-gui; $(MAKE) $@
	@cd gui; $(MAKE) $@

install:
	@cd non-gui; $(MAKE) $@
	@cd gui; $(MAKE) $@

clean:
	@cd non-gui; $(MAKE) $@
	@cd gui; $(MAKE) $@

depend:
	@cd non-gui; $(MAKE) $@
	@cd gui; $(MAKE) $@
