/*
Copyright (c) 2004 Tino, bayside
All rights reserved.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __BAYGUI_COLOR_H__
#define __BAYGUI_COLOR_H__

// 部品の初期値

#define DEFAULT_TRANSCOLOR 0x00000000
#define DEFAULT_FORECOLOR  0xff000000
#define DEFAULT_BACKCOLOR  0xffc0c0c0

// システム標準16色に準拠

#define COLOR_BLACK     0xff000000
#define COLOR_MAROON    0xff800000
#define COLOR_GREEN     0xff008000
#define COLOR_OLIVE     0xff808000
#define COLOR_NAVY      0xff000080
#define COLOR_PURPLE    0xff800080
#define COLOR_TEAL      0xff008080
#define COLOR_LIGHTGRAY 0xffC0C0C0
#define COLOR_GRAY      0xff808080
#define COLOR_RED       0xffff0000
#define COLOR_GREEN     0xff00ff00
#define COLOR_YELLOW    0xffffff00
#define COLOR_BLUE      0xff0000ff
#define COLOR_MAGENDA   0xffff00ff
#define COLOR_CYAN      0xff00ffff
#define COLOR_WHITE     0xffffffff

// 色要素取得用のちょっとしたマクロ

#define getAlpha(c) (c >> 24)
#define getRed(c)   (c >> 16 & 0xff)
#define getGreen(c) (c >>  8 & 0xff)
#define getBlue(c)  (c       & 0xff)

#endif  // __BAYGUI_COLOR_H__
