all:
	@cd hello; $(MAKE) $@
	@cd kanji; $(MAKE) $@

install:
	@cd hello; $(MAKE) $@
	#@cd kanji; $(MAKE) $@

clean:
	@cd hello; $(MAKE) $@
	@cd kanji; $(MAKE) $@

depend:
	@cd hello; $(MAKE) $@
	@cd kanji; $(MAKE) $@
