// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __SimpleShape__
#define __SimpleShape__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  class SimpleShape;
  class Vector;
  class Vertex;
}

class SimpleShape : public ::java::lang::Object
{
public:
  virtual void CreateDonuts (jint);
  virtual JArray< ::Vertex *> *GetVB () { return vertices; }
  virtual jintArray GetIndices () { return indices; }
private:
  static ::Vector *CalcNormal (::Vector *, ::Vector *, ::Vector *);
public:
  void CreateBoundingBox (JArray< ::Vertex *> *);
  void CreateBoundingSphere (JArray< ::Vertex *> *, jint);
  SimpleShape ();
public: // actually package-private
  JArray< ::Vertex *> * __attribute__((aligned(__alignof__( ::java::lang::Object )))) vertices;
  jintArray indices;
public:

  static ::java::lang::Class class$;
};

#endif /* __SimpleShape__ */
