// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __TLVertex__
#define __TLVertex__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  class TLVertex;
}

class TLVertex : public ::java::lang::Object
{
public:
  TLVertex ();
public: // actually package-private
  jint __attribute__((aligned(__alignof__( ::java::lang::Object ))))  x;
  jint y;
  jint z;
  jint r;
  jint g;
  jint b;
  jint s;
  jint sr;
  jint sg;
  jint sb;
  jint u;
  jint v;
  jint active;
public:

  static ::java::lang::Class class$;
};

#endif /* __TLVertex__ */
