all:
	@cd button; $(MAKE) $@
	@cd label; $(MAKE) $@
	@cd bitmap; $(MAKE) $@

install:
	@cd button; $(MAKE) $@
	@cd label; $(MAKE) $@
	@cd bitmap; $(MAKE) $@

clean:
	@cd button; $(MAKE) $@
	@cd label; $(MAKE) $@
	@cd bitmap; $(MAKE) $@

depend:
	@cd button; $(MAKE) $@
	@cd label; $(MAKE) $@
	@cd bitmap; $(MAKE) $@
