// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __A__
#define __A__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  class A;
}

class A : public ::java::lang::Object
{
public:
  A (jint, jint);
  virtual jint add ();
  virtual jint sub ();
  virtual jint mul ();
  virtual jint div ();
  static void main ();
  jint __attribute__((aligned(__alignof__( ::java::lang::Object ))))  num1;
  jint num2;

  static ::java::lang::Class class$;
};

#endif /* __A__ */
