// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __JNoiz2bg__
#define __JNoiz2bg__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  class JNoiz2bg;
  class JNoiz2bg$Board;
}

class JNoiz2bg : public ::java::lang::Object
{
public: // actually package-private
  static void initBackground ();
  static void addBoard (jint, jint, jint, jint, jint);
  static void setStageBackground (jint);
  static void moveBackground ();
  static void clearBuffer (jintArray);
  static void drawBoxAlpha (jintArray, jint, jint, jint, jint, jint, jint);
  static void drawBackground (jintArray);
private:
  static jint AlphaBlend (jint, jint, jint);
public:
  static void main (JArray< ::java::lang::String *> *);
  JNoiz2bg ();
public: // actually package-private
  static const jint BOARD_MAX = 256L;
  static const jint NOT_EXIST = -1L;
  static const jint FPS = 30L;
  static const jint SCREEN_W = 256L;
  static const jint SCREEN_H = 256L;
  static jint bdIdx;
  static jint boardMx;
  static jint boardMy;
  static jint boardRepx;
  static jint boardRepy;
  static jint boardRepXn;
  static jint boardRepYn;
  static JArray< ::JNoiz2bg$Board *> *board;

  friend class JNoiz2bg$Board;
public:

  static ::java::lang::Class class$;
};

#endif /* __JNoiz2bg__ */
