// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __SimpleCanvas__
#define __SimpleCanvas__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  class SimpleCanvas;
}

class SimpleCanvas : public ::java::lang::Object
{
public:
  static jboolean create (jintArray, ::java::lang::String *, jint, jint);
  static jboolean doEvents ();
  static void invalidate () { }
  SimpleCanvas ();

  static ::java::lang::Class class$;
};

#endif /* __SimpleCanvas__ */
