// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_awt_FontMetrics__
#define __java_awt_FontMetrics__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      class FontMetrics;
    }
  }
}

class java::awt::FontMetrics : public ::java::lang::Object
{
private:
  void create (jbyteArray);
public:
  FontMetrics ();
  virtual jint getCharWidth (jchar);
  virtual jint getWidth (::java::lang::String *);
  virtual jint getHeight (::java::lang::String *);
  virtual jint getFontStyle () { return fontStyle; }
  virtual void setFontStyle (jint);
  static jint offsetListLength;
  static jintArray offsetList;
  static jbyteArray defaultFontData;
private:
  jint __attribute__((aligned(__alignof__( ::java::lang::Object ))))  fontStyle;
public:

  static ::java::lang::Class class$;
};

#endif /* __java_awt_FontMetrics__ */
