TARGET = 1LINESH
SOURCES         = main.cpp          \
                  OneLineShell.cpp  \
                  Command.cpp       \
                  DisplayWindow.cpp \
                  CommandHistory.cpp

MONADIR = ../../..
include $(MONADIR)/env/monapi-bn2.inc

INSTDIR = $(BINDIR)/root/SERVERS

include dependencies
