#include "hash.h"
#include <stdio.h>
#include "html.h"
static HashItem_si MyHashItem[] = {
  /* 0 */ {"option_int",HTML_OPTION_INT,&MyHashItem[1]},
  /* 1 */ {"/form_int",HTML_N_FORM_INT,&MyHashItem[2]},
  /* 2 */ {"/kbd",HTML_NOP,&MyHashItem[3]},
  /* 3 */ {"dd",HTML_DD,&MyHashItem[4]},
  /* 4 */ {"/dir",HTML_N_UL,NULL},
  /* 5 */ {"/body",HTML_N_BODY,&MyHashItem[6]},
  /* 6 */ {"noframes",HTML_NOFRAMES,NULL},
  /* 7 */ {"base",HTML_BASE,NULL},
  /* 8 */ {"/div",HTML_N_DIV,NULL},
  /* 9 */ {"tbody",HTML_TBODY,&MyHashItem[10]},
  /* 10 */ {"meta",HTML_META,&MyHashItem[11]},
  /* 11 */ {"i",HTML_I,NULL},
  /* 12 */ {"/_symbol",HTML_N_SYMBOL,&MyHashItem[13]},
  /* 13 */ {"sup",HTML_SUP,&MyHashItem[14]},
  /* 14 */ {"/p",HTML_N_P,NULL},
  /* 15 */ {"/q",HTML_N_Q,NULL},
  /* 16 */ {"input_alt",HTML_INPUT_ALT,&MyHashItem[17]},
  /* 17 */ {"dl",HTML_DL,NULL},
  /* 18 */ {"/tbody",HTML_N_TBODY,&MyHashItem[19]},
  /* 19 */ {"/s",HTML_N_S,NULL},
  /* 20 */ {"del",HTML_DEL,&MyHashItem[21]},
  /* 21 */ {"xmp",HTML_XMP,&MyHashItem[22]},
  /* 22 */ {"br",HTML_BR,NULL},
  /* 23 */ {"link",HTML_LINK,&MyHashItem[24]},
  /* 24 */ {"/u",HTML_N_U,&MyHashItem[25]},
  /* 25 */ {"em",HTML_EM,NULL},
  /* 26 */ {"title_alt",HTML_TITLE_ALT,&MyHashItem[27]},
  /* 27 */ {"caption",HTML_CAPTION,&MyHashItem[28]},
  /* 28 */ {"plaintext",HTML_PLAINTEXT,&MyHashItem[29]},
  /* 29 */ {"p",HTML_P,NULL},
  /* 30 */ {"q",HTML_Q,&MyHashItem[31]},
  /* 31 */ {"blockquote",HTML_BLQ,&MyHashItem[32]},
  /* 32 */ {"menu",HTML_UL,NULL},
  /* 33 */ {"/colgroup",HTML_N_COLGROUP,&MyHashItem[34]},
  /* 34 */ {"dfn",HTML_NOP,NULL},
  /* 35 */ {"s",HTML_S,&MyHashItem[36]},
  /* 36 */ {"strong",HTML_STRONG,NULL},
  /* 37 */ {"dt",HTML_DT,NULL},
  /* 38 */ {"u",HTML_U,NULL},
  /* 39 */ {"/map",HTML_N_MAP,&MyHashItem[40]},
  /* 40 */ {"/frameset",HTML_N_FRAMESET,&MyHashItem[41]},
  /* 41 */ {"/ol",HTML_N_OL,NULL},
  /* 42 */ {"/td",HTML_N_TD,NULL},
  /* 43 */ {"li",HTML_LI,NULL},
  /* 44 */ {"html",HTML_BODY,&MyHashItem[45]},
  /* 45 */ {"hr",HTML_HR,NULL},
  /* 46 */ {"/strong",HTML_N_STRONG,NULL},
  /* 47 */ {"/th",HTML_N_TH,&MyHashItem[48]},
  /* 48 */ {"option",HTML_OPTION,&MyHashItem[49]},
  /* 49 */ {"kbd",HTML_NOP,&MyHashItem[50]},
  /* 50 */ {"dir",HTML_UL,NULL},
  /* 51 */ {"col",HTML_COL,NULL},
  /* 52 */ {"/caption",HTML_N_CAPTION,&MyHashItem[53]},
  /* 53 */ {"div",HTML_DIV,NULL},
  /* 54 */ {"head",HTML_HEAD,&MyHashItem[55]},
  /* 55 */ {"ol",HTML_OL,&MyHashItem[56]},
  /* 56 */ {"/ul",HTML_N_UL,NULL},
  /* 57 */ {"/ins",HTML_N_INS,&MyHashItem[58]},
  /* 58 */ {"area",HTML_AREA,NULL},
  /* 59 */ {"pre_plain",HTML_PRE_PLAIN,&MyHashItem[60]},
  /* 60 */ {"td",HTML_TD,&MyHashItem[61]},
  /* 61 */ {"/option",HTML_N_OPTION,NULL},
  /* 62 */ {"/noframes",HTML_N_NOFRAMES,NULL},
  /* 63 */ {"/tr",HTML_N_TR,&MyHashItem[64]},
  /* 64 */ {"nobr",HTML_NOBR,NULL},
  /* 65 */ {"img_alt",HTML_IMG_ALT,&MyHashItem[66]},
  /* 66 */ {"table_alt",HTML_TABLE_ALT,&MyHashItem[67]},
  /* 67 */ {"th",HTML_TH,&MyHashItem[68]},
  /* 68 */ {"script",HTML_SCRIPT,&MyHashItem[69]},
  /* 69 */ {"/tt",HTML_NOP,NULL},
  /* 70 */ {"code",HTML_NOP,NULL},
  /* 71 */ {"samp",HTML_NOP,NULL},
  /* 72 */ {"textarea",HTML_TEXTAREA,NULL},
  /* 73 */ {"textarea_int",HTML_TEXTAREA_INT,NULL},
  /* 74 */ {"table",HTML_TABLE,&MyHashItem[75]},
  /* 75 */ {"img",HTML_IMG,&MyHashItem[76]},
  /* 76 */ {"/blockquote",HTML_N_BLQ,NULL},
  /* 77 */ {"applet",HTML_APPLET,&MyHashItem[78]},
  /* 78 */ {"map",HTML_MAP,&MyHashItem[79]},
  /* 79 */ {"ul",HTML_UL,NULL},
  /* 80 */ {"/script",HTML_N_SCRIPT,&MyHashItem[81]},
  /* 81 */ {"center",HTML_CENTER,NULL},
  /* 82 */ {"/table",HTML_N_TABLE,&MyHashItem[83]},
  /* 83 */ {"cite",HTML_NOP,&MyHashItem[84]},
  /* 84 */ {"/h1",HTML_N_H,NULL},
  /* 85 */ {"tr",HTML_TR,&MyHashItem[86]},
  /* 86 */ {"/h2",HTML_N_H,NULL},
  /* 87 */ {"image",HTML_IMG,&MyHashItem[88]},
  /* 88 */ {"/h3",HTML_N_H,NULL},
  /* 89 */ {"pre_int",HTML_PRE_INT,&MyHashItem[90]},
  /* 90 */ {"/font",HTML_N_FONT,&MyHashItem[91]},
  /* 91 */ {"tt",HTML_NOP,&MyHashItem[92]},
  /* 92 */ {"/h4",HTML_N_H,NULL},
  /* 93 */ {"body",HTML_BODY,&MyHashItem[94]},
  /* 94 */ {"/form",HTML_N_FORM,&MyHashItem[95]},
  /* 95 */ {"/h5",HTML_N_H,NULL},
  /* 96 */ {"/h6",HTML_N_H,NULL},
  /* 97 */ {"frame",HTML_FRAME,NULL},
  /* 98 */ {"/textarea_int",HTML_N_TEXTAREA_INT,&MyHashItem[99]},
  /* 99 */ {"/img_alt",HTML_N_IMG_ALT,&MyHashItem[100]},
  /* 100 */ {"/center",HTML_N_CENTER,NULL},
  /* 101 */ {"/pre",HTML_N_PRE,NULL},
  /* 102 */ {"tfoot",HTML_TFOOT,NULL},
  /* 103 */ {"ins",HTML_INS,NULL},
  /* 104 */ {"/var",HTML_NOP,NULL},
  /* 105 */ {"h1",HTML_H,NULL},
  /* 106 */ {"/tfoot",HTML_N_TFOOT,&MyHashItem[107]},
  /* 107 */ {"input",HTML_INPUT,&MyHashItem[108]},
  /* 108 */ {"h2",HTML_H,NULL},
  /* 109 */ {"h3",HTML_H,NULL},
  /* 110 */ {"h4",HTML_H,NULL},
  /* 111 */ {"h5",HTML_H,NULL},
  /* 112 */ {"internal",HTML_INTERNAL,&MyHashItem[113]},
  /* 113 */ {"h6",HTML_H,NULL},
  /* 114 */ {"div_int",HTML_DIV_INT,&MyHashItem[115]},
  /* 115 */ {"select_int",HTML_SELECT_INT,&MyHashItem[116]},
  /* 116 */ {"/pre_int",HTML_N_PRE_INT,NULL},
  /* 117 */ {"/menu",HTML_N_UL,NULL},
  /* 118 */ {"form_int",HTML_FORM_INT,&MyHashItem[119]},
  /* 119 */ {"/sub",HTML_N_SUB,NULL},
  /* 120 */ {"style",HTML_STYLE,&MyHashItem[121]},
  /* 121 */ {"address",HTML_BR,NULL},
  /* 122 */ {"/textarea",HTML_N_TEXTAREA,NULL},
  /* 123 */ {"/input_alt",HTML_N_INPUT_ALT,NULL},
  /* 124 */ {"doctype",HTML_DOCTYPE,&MyHashItem[125]},
  /* 125 */ {"/style",HTML_N_STYLE,NULL},
  /* 126 */ {"/html",HTML_N_BODY,NULL},
  /* 127 */ {"pre",HTML_PRE,&MyHashItem[128]},
  /* 128 */ {"title",HTML_TITLE,NULL},
  /* 129 */ {"select",HTML_SELECT,NULL},
  /* 130 */ {"/div_int",HTML_N_DIV_INT,&MyHashItem[131]},
  /* 131 */ {"var",HTML_NOP,NULL},
  /* 132 */ {"/title",HTML_N_TITLE,NULL},
  /* 133 */ {"embed",HTML_EMBED,&MyHashItem[134]},
  /* 134 */ {"/sup",HTML_N_SUP,&MyHashItem[135]},
  /* 135 */ {"colgroup",HTML_COLGROUP,&MyHashItem[136]},
  /* 136 */ {"/head",HTML_N_HEAD,&MyHashItem[137]},
  /* 137 */ {"isindex",HTML_ISINDEX,NULL},
  /* 138 */ {"strike",HTML_S,&MyHashItem[139]},
  /* 139 */ {"listing",HTML_LISTING,NULL},
  /* 140 */ {"bgsound",HTML_BGSOUND,NULL},
  /* 141 */ {"/address",HTML_BR,NULL},
  /* 142 */ {"thead",HTML_THEAD,&MyHashItem[143]},
  /* 143 */ {"wbr",HTML_WBR,&MyHashItem[144]},
  /* 144 */ {"/del",HTML_N_DEL,&MyHashItem[145]},
  /* 145 */ {"/nobr",HTML_N_NOBR,&MyHashItem[146]},
  /* 146 */ {"/select",HTML_N_SELECT,&MyHashItem[147]},
  /* 147 */ {"frameset",HTML_FRAMESET,&MyHashItem[148]},
  /* 148 */ {"/xmp",HTML_N_XMP,NULL},
  /* 149 */ {"/code",HTML_NOP,NULL},
  /* 150 */ {"_symbol",HTML_SYMBOL,&MyHashItem[151]},
  /* 151 */ {"/thead",HTML_N_THEAD,&MyHashItem[152]},
  /* 152 */ {"/samp",HTML_NOP,&MyHashItem[153]},
  /* 153 */ {"/dfn",HTML_NOP,&MyHashItem[154]},
  /* 154 */ {"_id",HTML_NOP,NULL},
  /* 155 */ {"/strike",HTML_N_S,&MyHashItem[156]},
  /* 156 */ {"/a",HTML_N_A,NULL},
  /* 157 */ {"/select_int",HTML_N_SELECT_INT,&MyHashItem[158]},
  /* 158 */ {"sub",HTML_SUB,&MyHashItem[159]},
  /* 159 */ {"/b",HTML_N_B,NULL},
  /* 160 */ {"/internal",HTML_N_INTERNAL,NULL},
  /* 161 */ {"/pre_plain",HTML_N_PRE_PLAIN,&MyHashItem[162]},
  /* 162 */ {"font",HTML_FONT,&MyHashItem[163]},
  /* 163 */ {"/dl",HTML_N_DL,NULL},
  /* 164 */ {"form",HTML_FORM,&MyHashItem[165]},
  /* 165 */ {"/cite",HTML_NOP,&MyHashItem[166]},
  /* 166 */ {"a",HTML_A,NULL},
  /* 167 */ {"b",HTML_B,NULL},
  /* 168 */ {"/listing",HTML_N_LISTING,&MyHashItem[169]},
  /* 169 */ {"/em",HTML_N_EM,&MyHashItem[170]},
  /* 170 */ {"/i",HTML_N_I,NULL},
};

static HashItem_si *MyHashItemTbl[] = {
  &MyHashItem[0],
  &MyHashItem[5],
  NULL,
  &MyHashItem[7],
  &MyHashItem[8],
  &MyHashItem[9],
  &MyHashItem[12],
  &MyHashItem[15],
  &MyHashItem[16],
  &MyHashItem[18],
  &MyHashItem[20],
  &MyHashItem[23],
  &MyHashItem[26],
  &MyHashItem[30],
  &MyHashItem[33],
  &MyHashItem[35],
  &MyHashItem[37],
  &MyHashItem[38],
  &MyHashItem[39],
  NULL,
  &MyHashItem[42],
  &MyHashItem[43],
  &MyHashItem[44],
  &MyHashItem[46],
  &MyHashItem[47],
  NULL,
  &MyHashItem[51],
  NULL,
  &MyHashItem[52],
  NULL,
  &MyHashItem[54],
  &MyHashItem[57],
  &MyHashItem[59],
  &MyHashItem[62],
  &MyHashItem[63],
  NULL,
  &MyHashItem[65],
  &MyHashItem[70],
  &MyHashItem[71],
  &MyHashItem[72],
  &MyHashItem[73],
  &MyHashItem[74],
  &MyHashItem[77],
  NULL,
  &MyHashItem[80],
  &MyHashItem[82],
  &MyHashItem[85],
  &MyHashItem[87],
  &MyHashItem[89],
  &MyHashItem[93],
  &MyHashItem[96],
  &MyHashItem[97],
  &MyHashItem[98],
  &MyHashItem[101],
  &MyHashItem[102],
  &MyHashItem[103],
  &MyHashItem[104],
  &MyHashItem[105],
  &MyHashItem[106],
  &MyHashItem[109],
  &MyHashItem[110],
  &MyHashItem[111],
  &MyHashItem[112],
  NULL,
  &MyHashItem[114],
  &MyHashItem[117],
  NULL,
  NULL,
  &MyHashItem[118],
  &MyHashItem[120],
  NULL,
  &MyHashItem[122],
  &MyHashItem[123],
  &MyHashItem[124],
  &MyHashItem[126],
  NULL,
  NULL,
  &MyHashItem[127],
  &MyHashItem[129],
  NULL,
  &MyHashItem[130],
  &MyHashItem[132],
  &MyHashItem[133],
  &MyHashItem[138],
  &MyHashItem[140],
  &MyHashItem[141],
  &MyHashItem[142],
  NULL,
  NULL,
  &MyHashItem[149],
  &MyHashItem[150],
  &MyHashItem[155],
  &MyHashItem[157],
  NULL,
  &MyHashItem[160],
  NULL,
  &MyHashItem[161],
  &MyHashItem[164],
  &MyHashItem[167],
  &MyHashItem[168],
};

Hash_si tagtable = {100, MyHashItemTbl};
