// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_io_PrintStream__
#define __java_io_PrintStream__

#pragma interface

#include <java/lang/Object.h>

class java::io::PrintStream : public ::java::lang::Object
{
public:
  PrintStream (::java::lang::Object *);
  virtual void print (::java::lang::String *);
  virtual void print (jint);
  virtual void println ();
  virtual void println (::java::lang::String *);
  virtual void println (jint);

  static ::java::lang::Class class$;
};

#endif /* __java_io_PrintStream__ */
