all:
	@cd kernel; $(MAKE) $@
	@cd lib; $(MAKE) $@
	@cd servers; $(MAKE) $@

install:
	@cd kernel; $(MAKE) $@
	@cd lib; $(MAKE) $@
	@cd servers; $(MAKE) $@

clean:
	@cd kernel; $(MAKE) $@
	@cd lib; $(MAKE) $@
	@cd servers; $(MAKE) $@

distclean:
	@cd kernel; $(MAKE) $@
	@cd lib; $(MAKE) $@
	@cd servers; $(MAKE) $@

depend:
	@cd kernel; $(MAKE) $@
	@cd lib; $(MAKE) $@
	@cd servers; $(MAKE) $@
