// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_lang_Object__
#define __java_lang_Object__

#pragma interface

class java::lang::Object
{
public:  // actually protected
  virtual void finalize () { }
public:
  Object () { }
  ::java::lang::Class *getClass ();
  virtual jint hashCode ();
  virtual jboolean equals (::java::lang::Object *);
  virtual ::java::lang::String *toString ();

  static ::java::lang::Class class$;
};

#endif /* __java_lang_Object__ */
