SOURCES = assert/assert.c ctype/isalnum.c ctype/isalpha.c ctype/isascii.c \
	  ctype/isblank.c ctype/iscntrl.c ctype/isdigit.c ctype/isgraph.c \
	  ctype/islower.c ctype/isprint.c ctype/ispunct.c ctype/isspace.c \
	  ctype/isupper.c ctype/isxdigit.c ctype/tolower.c ctype/toupper.c \
	  math/acos.c math/asin.c math/atan.c math/atan2.c math/fpclassify.c \
	  math/ceil.c math/cos.c math/cosh.c math/exp.c math/fabs.c \
	  math/floor.c math/fmod.c math/frexp.c math/ldexp.c math/log.c \
	  math/log2.c math/log10.c math/modf.c math/pow.c math/sin.c \
	  math/sinh.c math/round.c math/nearbyint.c \
	  math/sqrt.c math/tan.c math/tanh.c stdio/fclose.c stdio/fileno.c \
	  stdio/fopen.c stdio/fread.c stdio/futil.c stdio/fwrite.c \
	  stdio/fseek.c stdio/rewind.c stdio/feof.c stdio/ferror.c \
	  stdio/fflush.c stdio/clearerr.c stdio/sprintf.c \
	  stdio/fgetc.c stdio/fgets.c stdio/fscanf.c  stdio/fputc.c \
	  stdio/putc.c stdio/putchar.c stdio/sscanf.c \
	  stdio/setbuf.c stdio/setvbuf.c stdio/perror.c \
	  stdio/freopen.c stdio/ftell.c stdio/fgetpos.c stdio/fsetpos.c \
	  stdio/fputs.c stdio/puts.c stdio/getc.c stdio/getchar.c \
	  stdio/vsprintf.c stdio/vsscanf.c stdio/vfprintf.c \
	  stdlib/abort.c stdlib/abs.c stdlib/atexit.c \
	  stdlib/atof.c stdlib/atoi.c stdlib/atol.c stdlib/bsearch.c \
	  stdlib/div.c stdlib/getenv.c stdlib/labs.c stdlib/ldiv.c \
	  stdlib/llabs.c stdlib/mblen.c stdlib/mbstowcs.c stdlib/mbtowc.c \
	  stdlib/strtod.c stdlib/strtol.c stdlib/strtoul.c stdlib/strtoi.c \
	  stdlib/wcstombs.c stdlib/wctomb.c string/memccpy.c string/memchr.c \
	  stdlib/putenv.c stdlib/qsort.c stdlib/rand.c stdlib/srand.c \
	  string/memrchr.c string/nidastrfind.c string/strchr.c \
	  string/strcoll.c string/strerror.c string/strlcat.c \
	  string/strlcpy.c string/strncat.c string/strpbrk.c string/strrchr.c \
	  string/strtok.c string/strtok_r.c string/strxfrm.c string/strdup.c \
	  time/clock.c time/time.c time/time_util.c time/gmtime_r.c \
	  time/gmtime.c time/mktime.c time/difftime.c time/strftime.c \
	  inttypes/imaxabs.c \
	  stdarg/stdarg.c private/uitosn.c private/itos.c \
	  private/ftos.c private/strcpy2.c private/memswap.c \
	  private/logprintf.c \
	  private/alloca.c \
	  errno/errno.c \
	  wchar/wcscpy.c wchar/wcsncpy.c wchar/wmemcpy.c wchar/wmemmove.c \
	  fenv/feclearexcept.c fenv/fegetexceptflag.c fenv/feraiseexcept.c \
	  fenv/fesetexceptflag.c fenv/fetestexcept.c fenv/fegetround.c \
	  fenv/fesetround.c fenv/fesetenv.c fenv/fegetenv.c fenv/feupdateenv.c \
	  fenv/feholdexcept.c \
	  setjmp/setjmp_c.c \
	  dirent/opendir.c dirent/closedir.c dirent/dirutil.c dirent/readdir.c\
	  dirent/rewinddir.c dirent/telldir.c dirent/seekdir.c \
#	  inttypes/imaxdiv.c \
#	  string/strncmp.c string/strncpy.c string/strspn.c string/strstr.c \
#	  string/strcat.c string/strcmp.c string/strcspn.c string/strlen.c \
#	  string/memcmp.c string/memcpy.c string/memmove.c string/memset.c \
#	  string/strcpy.c \
