include Makefile.inc

all : userlib_mona HelloWorld_mona clock_mona jpegls_mona KeyBoardServer_mona map_mona MouseServer_mona noiz2bg_mona Reversi_mona ShellServer_mona NIC_mona waba_mona

userlib_mona :
	cd userlib; $(MAKE)

HelloWorld_mona :
	cd HelloWorld; $(MAKE)

clock_mona :
	cd clock; $(MAKE)

jpegls_mona :
	cd jpegls; $(MAKE)

KeyBoardServer_mona :
	cd KeyBoardServer; $(MAKE)

map_mona :
	cd MapServer; $(MAKE)

MouseServer_mona :
	cd MouseServer; $(MAKE)

noiz2bg_mona :
	cd noiz2bg; $(MAKE)

Reversi_mona :
	cd Reversi; $(MAKE)

ShellServer_mona :
	cd ShellServer; $(MAKE)

NIC_mona :
	cd NIC; $(MAKE)

waba_mona :
	cd waba; $(MAKE)

clean :
	(cd userlib;        $(MAKE) clean)
	(cd HelloWorld;     $(MAKE) clean)
	(cd clock;          $(MAKE) clean)
	(cd jpegls;         $(MAKE) clean)
	(cd KeyBoardServer; $(MAKE) clean)
	(cd MapServer;      $(MAKE) clean)
	(cd MouseServer;    $(MAKE) clean)
	(cd noiz2bg;        $(MAKE) clean)
	(cd Reversi;        $(MAKE) clean)
	(cd ShellServer;    $(MAKE) clean)
	(cd NIC;            $(MAKE) clean)
	(cd waba;           $(MAKE) clean)


