all:
	@cd ne2k; $(MAKE) $@

install:
	@cd ne2k; $(MAKE) $@

clean: touchdepend
	@cd ne2k; $(MAKE) $@

depend: touchdepend
	@cd ne2k; $(MAKE) $@

distclean:
	rm -f ne2k/dependencies

touchdepend:
	touch ne2k/dependencies
