// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __Render__
#define __Render__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  class Render;
  class VERTEX;
  class TLVERTEX;
  class Matrix;
}

class Render : public ::java::lang::Object
{
public:
  Render (jint, jint);
  static void Clear ();
  static void SetTransform (::Matrix *);
  static void DrawIndexedPrimitive (jint, JArray< ::VERTEX *> *, jshortArray);
  static void Transform (JArray< ::VERTEX *> *);
private:
  static void DrawPolyLine (::TLVERTEX *, ::TLVERTEX *, ::TLVERTEX *, ::TLVERTEX *);
  static void DrawPolyAALine (::TLVERTEX *, ::TLVERTEX *, ::TLVERTEX *, ::TLVERTEX *);
  static void DrawLine (::TLVERTEX *, ::TLVERTEX *, jint);
  static void DrawAALine (::TLVERTEX *, ::TLVERTEX *, jint);
  static jint AlphaBlend (jint, jint, jint);
public: // actually package-private
  static const jint PRIMITIVE_POLYLINE = 2L;
  static const jint PRIMITIVE_POLYAALINE = 3L;
  static ::Matrix *mMaster;
public:
  static jintArray pbuf;
private:
  static jint BUFFERW;
  static jint BUFFERH;
  static JArray< ::TLVERTEX *> *tvtx;
public:

  static ::java::lang::Class class$;
};

#endif /* __Render__ */
