// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __SimpleShape__
#define __SimpleShape__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  class SimpleShape;
  class Vector;
  class VERTEX;
}

class SimpleShape : public ::java::lang::Object
{
public:
  virtual void CreateSphere (jint);
  virtual JArray< ::VERTEX *> *GetVB () { return vertices; }
  virtual jshortArray GetIndices () { return indices; }
private:
  static ::Vector *CalcNormal (::Vector *, ::Vector *, ::Vector *);
public:
  SimpleShape ();
public: // actually package-private
  JArray< ::VERTEX *> * __attribute__((aligned(__alignof__( ::java::lang::Object )))) vertices;
  jshortArray indices;
public:
  static jfloat min;
  static jfloat max;

  static ::java::lang::Class class$;
};

#endif /* __SimpleShape__ */
