// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __Render__
#define __Render__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  class Render;
  class TLVertex;
  class Vertex;
  class Texture;
  class Matrix;
}

class Render : public ::java::lang::Object
{
public:
  Render (jint, jint);
  static void SetTexture (::Texture *);
  static void Clear ();
  static void SetTransform (jint, ::Matrix *);
  static void DrawIndexedPrimitive (jint, JArray< ::Vertex *> *, jintArray);
  static JArray< ::TLVertex *> *TransformAndLighting (JArray< ::Vertex *> *);
private:
  static void DrawPolygon (::TLVertex *, ::TLVertex *, ::TLVertex *);
  static void ScanEdge (::TLVertex *, ::TLVertex *);
public:
  static void SetViewPort (jint, jint, jint, jint);
public: // actually package-private
  static const jint PRIMITIVE_POLYGON = 1L;
  static const jint TRANSFORM_WORLD = 0L;
  static const jint TRANSFORM_VIEW = 1L;
  static const jint TRANSFORM_PROJ = 2L;
  static jintArray pbuf;
private:
  static jintArray zbuf;
  static jintArray tbuf;
  static jint BUFFERW;
  static jint BUFFERH;
  static jint CENTERX;
  static jint CENTERY;
  static jint TEXTUREW;
  static jint TEXTUREH;
  static jint TEXMASKW;
  static jint TEXMASKH;
  static jint TEXSHIFT;
  static jint VIEWPORTL;
  static jint VIEWPORTR;
  static jint VIEWPORTT;
  static jint VIEWPORTB;
  static jint VIEWPORTW;
  static jint VIEWPORTH;
  static jint VIEWPORTCX;
  static jint VIEWPORTCY;
  static jintArray min;
  static jintArray max;
  static jintArray minz;
  static jintArray maxz;
  static jintArray ming;
  static jintArray maxg;
  static jintArray minu;
  static jintArray maxu;
  static jintArray minv;
  static jintArray maxv;
  static jintArray mins;
  static jintArray maxs;
public: // actually package-private
  static ::Matrix *mWorld;
  static ::Matrix *mView;
  static ::Matrix *mMaster;
  static ::Matrix *mProj;
public:

  static ::java::lang::Class class$;
};

#endif /* __Render__ */
