#include "hash.h"
#include <stdio.h>
#include "funcname1.h"
static HashItem_si MyHashItem[] = {
  /* 0 */ {"SUSPEND",FUNCNAME_susp,&MyHashItem[1]},
  /* 1 */ {"SET_OPTION",FUNCNAME_setOpt,&MyHashItem[2]},
  /* 2 */ {"END",FUNCNAME_goLineL,NULL},
  /* 3 */ {"VIEW",FUNCNAME_vwSrc,NULL},
  /* 4 */ {"PREV_VISITED",FUNCNAME_prevVA,&MyHashItem[5]},
  /* 5 */ {"EXTERN",FUNCNAME_extbrz,NULL},
  /* 6 */ {"UNDO",FUNCNAME_undoPos,NULL},
  /* 7 */ {"SHELL",FUNCNAME_execsh,&MyHashItem[8]},
  /* 8 */ {"RIGHT",FUNCNAME_col1R,&MyHashItem[9]},
  /* 9 */ {"PREV_WORD",FUNCNAME_movLW,&MyHashItem[10]},
  /* 10 */ {"LEFT",FUNCNAME_col1L,&MyHashItem[11]},
  /* 11 */ {"INTERRUPT",FUNCNAME_susp,NULL},
  /* 12 */ {"TAB_GOTO_RELATIVE",FUNCNAME_tabrURL,NULL},
  /* 13 */ {"NEXT_UP",FUNCNAME_nextU,NULL},
  /* 14 */ {"CLOSE_TAB_MOUSE",FUNCNAME_closeTMs,NULL},
  /* 15 */ {"DOWN",FUNCNAME_ldown1,NULL},
  /* 16 */ {"HISTORY",FUNCNAME_ldHist,NULL},
  /* 17 */ {"SEARCH",FUNCNAME_srchfor,&MyHashItem[18]},
  /* 18 */ {"NEXT_VISITED",FUNCNAME_nextVA,&MyHashItem[19]},
  /* 19 */ {"NEXT_LEFT_UP",FUNCNAME_nextLU,&MyHashItem[20]},
  /* 20 */ {"MOVE_UP",FUNCNAME_movU,&MyHashItem[21]},
  /* 21 */ {"DOWNLOAD",FUNCNAME_svSrc,NULL},
  /* 22 */ {"VIEW_IMAGE",FUNCNAME_followI,&MyHashItem[23]},
  /* 23 */ {"MARK",FUNCNAME__mark,&MyHashItem[24]},
  /* 24 */ {"INFO",FUNCNAME_pginfo,NULL},
  /* 25 */ {"VERSION",FUNCNAME_dispVer,&MyHashItem[26]},
  /* 26 */ {"BEGIN",FUNCNAME_goLineF,NULL},
  /* 27 */ {"REDRAW",FUNCNAME_rdrwSc,NULL},
  /* 28 */ {"QUIT",FUNCNAME_qquitfm,&MyHashItem[29]},
  /* 29 */ {"DOWNLOAD_LIST",FUNCNAME_ldDL,NULL},
  /* 30 */ {"REG_MARK",FUNCNAME_reMark,NULL},
  /* 31 */ {"MOVE_RIGHT",FUNCNAME_movR,NULL},
  /* 32 */ {"MARK_MID",FUNCNAME_chkNMID,&MyHashItem[33]},
  /* 33 */ {"LOAD",FUNCNAME_ldfile,NULL},
  /* 34 */ {"EXEC_SHELL",FUNCNAME_execsh,NULL},
  /* 35 */ {"VIEW_BOOKMARK",FUNCNAME_ldBmark,&MyHashItem[36]},
  /* 36 */ {"TAB_MOUSE",FUNCNAME_tabMs,&MyHashItem[37]},
  /* 37 */ {"STOP_IMAGE",FUNCNAME_stopI,NULL},
  /* 38 */ {"SHIFT_RIGHT",FUNCNAME_shiftr,&MyHashItem[39]},
  /* 39 */ {"SEARCH_NEXT",FUNCNAME_srchnxt,NULL},
  /* 40 */ {"PEEK",FUNCNAME_curURL,NULL},
  /* 41 */ {"DICT_WORD_AT",FUNCNAME_dictwordat,NULL},
  /* 42 */ {"SOURCE",FUNCNAME_vwSrc,&MyHashItem[43]},
  /* 43 */ {"SAVE_LINK",FUNCNAME_svA,&MyHashItem[44]},
  /* 44 */ {"GOTO",FUNCNAME_goURL,&MyHashItem[45]},
  /* 45 */ {"ACCESSKEY",FUNCNAME_accessKey,NULL},
  /* 46 */ {"ABORT",FUNCNAME_quitfm,NULL},
  /* 47 */ {"MENU",FUNCNAME_mainMn,NULL},
  /* 48 */ {"PCMAP",FUNCNAME_pcmap,&MyHashItem[49]},
  /* 49 */ {"EXIT",FUNCNAME_quitfm,NULL},
  /* 50 */ {"LINE_INFO",FUNCNAME_curlno,&MyHashItem[51]},
  /* 51 */ {"ADD_BOOKMARK",FUNCNAME_adBmark,NULL},
  /* 52 */ {"WHEREIS",FUNCNAME_srchfor,&MyHashItem[53]},
  /* 53 */ {"SELECT_MENU",FUNCNAME_selMn,&MyHashItem[54]},
  /* 54 */ {"GOTO_LINE",FUNCNAME_goLine,NULL},
  /* 55 */ {"MOUSE",FUNCNAME_mouse,NULL},
  /* 56 */ {"PIPE_BUF",FUNCNAME_pipeBuf,&MyHashItem[57]},
  /* 57 */ {"LINK_BEGIN",FUNCNAME_topA,NULL},
  /* 58 */ {"PEEK_IMG",FUNCNAME_peekIMG,NULL},
  /* 59 */ {"CHARSET",FUNCNAME_docCSet,NULL},
  /* 60 */ {"GOTO_LINK",FUNCNAME_followA,&MyHashItem[61]},
  /* 61 */ {"EXTERN_LINK",FUNCNAME_linkbrz,NULL},
  /* 62 */ {"MARK_WORD",FUNCNAME_chkWORD,NULL},
  /* 63 */ {"MOVE_LIST_MENU",FUNCNAME_movlistMn,&MyHashItem[64]},
  /* 64 */ {"LINK_MENU",FUNCNAME_linkMn,NULL},
  /* 65 */ {"REDO",FUNCNAME_redoPos,&MyHashItem[66]},
  /* 66 */ {"BOOKMARK",FUNCNAME_ldBmark,NULL},
  /* 67 */ {"NEXT_RIGHT_DOWN",FUNCNAME_nextRD,&MyHashItem[68]},
  /* 68 */ {"NEXT_LEFT",FUNCNAME_nextL,&MyHashItem[69]},
  /* 69 */ {"COMMAND",FUNCNAME_execCmd,&MyHashItem[70]},
  /* 70 */ {"@@@",FUNCNAME_nulcmd,NULL},
  /* 71 */ {"RESHAPE",FUNCNAME_reshape,&MyHashItem[72]},
  /* 72 */ {"ALARM",FUNCNAME_setAlarm,NULL},
  /* 73 */ {"UP",FUNCNAME_lup1,&MyHashItem[74]},
  /* 74 */ {"SETENV",FUNCNAME_setEnv,&MyHashItem[75]},
  /* 75 */ {"RELOAD",FUNCNAME_reload,&MyHashItem[76]},
  /* 76 */ {"LIST",FUNCNAME_linkLst,NULL},
  /* 77 */ {"NEXT_PAGE",FUNCNAME_pgFore,&MyHashItem[78]},
  /* 78 */ {"MOVE_MOUSE",FUNCNAME_movMs,&MyHashItem[79]},
  /* 79 */ {"DISPLAY_IMAGE",FUNCNAME_dispI,NULL},
  /* 80 */ {"TAB_LEFT",FUNCNAME_tabL,&MyHashItem[81]},
  /* 81 */ {"PIPE_SHELL",FUNCNAME_pipesh,&MyHashItem[82]},
  /* 82 */ {"NEXT_TAB",FUNCNAME_nextT,&MyHashItem[83]},
  /* 83 */ {"NEXT_DOWN",FUNCNAME_nextD,NULL},
  /* 84 */ {"MAIN_MENU",FUNCNAME_mainMn,&MyHashItem[85]},
  /* 85 */ {"LIST_MENU",FUNCNAME_listMn,NULL},
  /* 86 */ {"REINIT",FUNCNAME_reinit,&MyHashItem[87]},
  /* 87 */ {"EDIT",FUNCNAME_editBf,NULL},
  /* 88 */ {"SAVE_IMAGE",FUNCNAME_svI,&MyHashItem[89]},
  /* 89 */ {"NEXT_MARK",FUNCNAME_nextMk,&MyHashItem[90]},
  /* 90 */ {"COOKIE",FUNCNAME_cooLst,NULL},
  /* 91 */ {"LINK_END",FUNCNAME_lastA,&MyHashItem[92]},
  /* 92 */ {"LINE_BEGIN",FUNCNAME_linbeg,&MyHashItem[93]},
  /* 93 */ {"DELETE_PREVBUF",FUNCNAME_deletePrevBuf,NULL},
  /* 94 */ {"WRAP_TOGGLE",FUNCNAME_wrapToggle,NULL},
  /* 95 */ {"DEFAULT_CHARSET",FUNCNAME_defCSet,NULL},
  /* 96 */ {"NOTHING",FUNCNAME_nulcmd,&MyHashItem[97]},
  /* 97 */ {"FRAME",FUNCNAME_rFrame,NULL},
  /* 98 */ {"SEARCH_PREV",FUNCNAME_srchprv,&MyHashItem[99]},
  /* 99 */ {"NEXT",FUNCNAME_nextBf,&MyHashItem[100]},
  /* 100 */ {"LINE_END",FUNCNAME_linend,NULL},
  /* 101 */ {"SELECT",FUNCNAME_selBuf,NULL},
  /* 102 */ {"PREV_TAB",FUNCNAME_prevT,&MyHashItem[103]},
  /* 103 */ {"MOVE_LEFT",FUNCNAME_movL,NULL},
  /* 104 */ {"SEARCH_BACK",FUNCNAME_srchbak,&MyHashItem[105]},
  /* 105 */ {"SAVE",FUNCNAME_svSrc,NULL},
  /* 106 */ {"SHIFT_LEFT",FUNCNAME_shiftl,&MyHashItem[107]},
  /* 107 */ {"READ_SHELL",FUNCNAME_readsh,&MyHashItem[108]},
  /* 108 */ {"PRINT",FUNCNAME_svBuf,&MyHashItem[109]},
  /* 109 */ {"MOVE_DOWN",FUNCNAME_movD,&MyHashItem[110]},
  /* 110 */ {"EDIT_SCREEN",FUNCNAME_editScr,NULL},
  /* 111 */ {"ISEARCH_BACK",FUNCNAME_isrchbak,NULL},
  /* 112 */ {"NEXT_LINK",FUNCNAME_nextA,NULL},
  /* 113 */ {"MSGS",FUNCNAME_msgs,NULL},
  /* 114 */ {"MULTIMAP",FUNCNAME_multimap,&MyHashItem[115]},
  /* 115 */ {"CENTER_H",FUNCNAME_ctrCsrH,NULL},
  /* 116 */ {"TAB_LINK",FUNCNAME_tabA,&MyHashItem[117]},
  /* 117 */ {"TAB_GOTO",FUNCNAME_tabURL,&MyHashItem[118]},
  /* 118 */ {"PREV_PAGE",FUNCNAME_pgBack,NULL},
  /* 119 */ {"SAVE_SCREEN",FUNCNAME_svBuf,NULL},
  /* 120 */ {"TAB_MENU",FUNCNAME_tabMn,&MyHashItem[121]},
  /* 121 */ {"SEARCH_FORE",FUNCNAME_srchfor,&MyHashItem[122]},
  /* 122 */ {"MOVE_UP1",FUNCNAME_movU1,&MyHashItem[123]},
  /* 123 */ {"MOVE_LEFT1",FUNCNAME_movL1,NULL},
  /* 124 */ {"PREV_MARK",FUNCNAME_prevMk,&MyHashItem[125]},
  /* 125 */ {"PEEK_LINK",FUNCNAME_peekURL,NULL},
  /* 126 */ {"MARK_URL",FUNCNAME_chkURL,NULL},
  /* 127 */ {"GOTO_RELATIVE",FUNCNAME_gorURL,NULL},
  /* 128 */ {"SUBMIT",FUNCNAME_submitForm,NULL},
  /* 129 */ {"NEXT_WORD",FUNCNAME_movRW,&MyHashItem[130]},
  /* 130 */ {"NEW_TAB",FUNCNAME_newT,&MyHashItem[131]},
  /* 131 */ {"HELP",FUNCNAME_ldhelp,NULL},
  /* 132 */ {"MOVE_DOWN1",FUNCNAME_movD1,NULL},
  /* 133 */ {"ISEARCH",FUNCNAME_isrchfor,NULL},
  /* 134 */ {"NEXT_RIGHT",FUNCNAME_nextR,&MyHashItem[135]},
  /* 135 */ {"CLOSE_TAB",FUNCNAME_closeT,&MyHashItem[136]},
  /* 136 */ {"CENTER_V",FUNCNAME_ctrCsrV,NULL},
  /* 137 */ {"MOVE_RIGHT1",FUNCNAME_movR1,NULL},
  /* 138 */ {"ESCMAP",FUNCNAME_escmap,&MyHashItem[139]},
  /* 139 */ {"ESCBMAP",FUNCNAME_escbmap,NULL},
  /* 140 */ {"MENU_MOUSE",FUNCNAME_menuMs,NULL},
  /* 141 */ {"PREV",FUNCNAME_prevBf,&MyHashItem[142]},
  /* 142 */ {"NULL",FUNCNAME_nulcmd,&MyHashItem[143]},
  /* 143 */ {"DICT_WORD",FUNCNAME_dictword,NULL},
  /* 144 */ {"PREV_LINK",FUNCNAME_prevA,NULL},
  /* 145 */ {"TAB_RIGHT",FUNCNAME_tabR,NULL},
  /* 146 */ {"MOUSE_TOGGLE",FUNCNAME_msToggle,&MyHashItem[147]},
  /* 147 */ {"BACK",FUNCNAME_backBf,NULL},
  /* 148 */ {"OPTIONS",FUNCNAME_ldOpt,&MyHashItem[149]},
  /* 149 */ {"DEFINE_KEY",FUNCNAME_defKey,NULL},
};

static HashItem_si *MyHashItemTbl[] = {
  &MyHashItem[0],
  NULL,
  NULL,
  NULL,
  NULL,
  &MyHashItem[3],
  &MyHashItem[4],
  &MyHashItem[6],
  &MyHashItem[7],
  &MyHashItem[12],
  &MyHashItem[13],
  &MyHashItem[14],
  &MyHashItem[15],
  &MyHashItem[16],
  &MyHashItem[17],
  &MyHashItem[22],
  &MyHashItem[25],
  &MyHashItem[27],
  &MyHashItem[28],
  &MyHashItem[30],
  &MyHashItem[31],
  NULL,
  &MyHashItem[32],
  NULL,
  &MyHashItem[34],
  NULL,
  NULL,
  &MyHashItem[35],
  &MyHashItem[38],
  &MyHashItem[40],
  &MyHashItem[41],
  &MyHashItem[42],
  &MyHashItem[46],
  &MyHashItem[47],
  &MyHashItem[48],
  &MyHashItem[50],
  NULL,
  &MyHashItem[52],
  NULL,
  &MyHashItem[55],
  &MyHashItem[56],
  &MyHashItem[58],
  &MyHashItem[59],
  &MyHashItem[60],
  &MyHashItem[62],
  &MyHashItem[63],
  NULL,
  &MyHashItem[65],
  &MyHashItem[67],
  &MyHashItem[71],
  &MyHashItem[73],
  &MyHashItem[77],
  &MyHashItem[80],
  &MyHashItem[84],
  &MyHashItem[86],
  &MyHashItem[88],
  &MyHashItem[91],
  &MyHashItem[94],
  &MyHashItem[95],
  &MyHashItem[96],
  &MyHashItem[98],
  NULL,
  &MyHashItem[101],
  NULL,
  &MyHashItem[102],
  &MyHashItem[104],
  NULL,
  NULL,
  &MyHashItem[106],
  &MyHashItem[111],
  NULL,
  &MyHashItem[112],
  NULL,
  &MyHashItem[113],
  &MyHashItem[114],
  &MyHashItem[116],
  &MyHashItem[119],
  &MyHashItem[120],
  NULL,
  &MyHashItem[124],
  &MyHashItem[126],
  &MyHashItem[127],
  &MyHashItem[128],
  NULL,
  &MyHashItem[129],
  &MyHashItem[132],
  &MyHashItem[133],
  NULL,
  &MyHashItem[134],
  &MyHashItem[137],
  &MyHashItem[138],
  &MyHashItem[140],
  &MyHashItem[141],
  NULL,
  NULL,
  &MyHashItem[144],
  &MyHashItem[145],
  &MyHashItem[146],
  NULL,
  &MyHashItem[148],
};

Hash_si functable = {100, MyHashItemTbl};
