#ifndef _SERVER_PM_
#define _SERVER_PM_

enum
{
	MSG_PM_CPU_IDLE = 0x5000,
	MSG_PM_CPU_BUSY,
	MSG_PM_SET_POWER_STATE,
	MSG_PM_GET_POWER_STATE,
	MSG_PM_ENABLE_PM,
	MSG_PM_DISABLE_PM,
	MSG_PM_ENABLE_DEVICE_PM,
	MSG_PM_DISABLE_DEVICE_PM,
	MSG_PM_GET_CAPABILITIES,
	MSG_PM_GET_POWER_STATUS,
};

#endif
