// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __A__
#define __A__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  class A;
}

class A : public ::java::lang::Object
{
public:
  static void main (JArray< ::java::lang::String *> *);
  A ();

  static ::java::lang::Class class$;
};

#endif /* __A__ */
