// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __org_monaos_KeyInfo__
#define __org_monaos_KeyInfo__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace org
  {
    namespace monaos
    {
      class KeyInfo;
    }
  }
};

class ::org::monaos::KeyInfo : public ::java::lang::Object
{
public:
  KeyInfo ();
  KeyInfo (jint, jint, jint);
  jint __attribute__((aligned(__alignof__( ::java::lang::Object ))))  keycode;
  jint modifiers;
  jint charcode;

  static ::java::lang::Class class$;
};

#endif /* __org_monaos_KeyInfo__ */
