// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __org_monaos_Keys__
#define __org_monaos_Keys__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace org
  {
    namespace monaos
    {
      class Keys;
      class KeyInfo;
    }
  }
};

class ::org::monaos::Keys : public ::java::lang::Object
{
public:
  virtual jchar ToChar (::org::monaos::KeyInfo *);
  virtual jboolean IsToChar (::org::monaos::KeyInfo *);
  virtual jchar ToChar (::org::monaos::KeyInfo *, jcharArray, jcharArray);
  virtual jboolean IsToChar (::org::monaos::KeyInfo *, jcharArray, jcharArray);
  virtual jintArray GetKeyMap (jint);
  virtual jintArray GetKeyMapE0 (jint);
  virtual jcharArray GetKeyTopMap (jint);
  virtual jcharArray GetKeyTopMapS (jint);
  Keys ();
  static const jint KEY_MODIFIER_DOWN = 1L;
  static const jint KEY_MODIFIER_UP = 2L;
  static const jint KEY_MODIFIER_SHIFT = 4L;
  static const jint KEY_MODIFIER_ALT = 8L;
  static const jint KEY_MODIFIER_CTRL = 16L;
  static const jint KEY_MODIFIER_WIN = 32L;
  static const jint KEY_MODIFIER_MENU = 64L;
  static const jint KEY_MODIFIER_CHAR = 128L;
  static const jint US102 = 0L;
  static const jint JP109 = 1L;
  static const jint Back = 8L;
  static const jint Tab = 9L;
  static const jint Enter = 13L;
  static const jint ShiftKey = 16L;
  static const jint ControlKey = 17L;
  static const jint Menu = 18L;
  static const jint Pause = 19L;
  static const jint CapsLock = 20L;
  static const jint KanaMode = 21L;
  static const jint KanjiMode = 25L;
  static const jint Escape = 27L;
  static const jint IMEConvert = 28L;
  static const jint IMENonconvert = 29L;
  static const jint IMEAceept = 30L;
  static const jint IMEModeChange = 31L;
  static const jint Space = 32L;
  static const jint PageUp = 33L;
  static const jint PageDown = 34L;
  static const jint End = 35L;
  static const jint Home = 36L;
  static const jint Left = 37L;
  static const jint Up = 38L;
  static const jint Right = 39L;
  static const jint Down = 40L;
  static const jint PrintScreen = 44L;
  static const jint Insert = 45L;
  static const jint Delete = 46L;
  static const jint D0 = 48L;
  static const jint D1 = 49L;
  static const jint D2 = 50L;
  static const jint D3 = 51L;
  static const jint D4 = 52L;
  static const jint D5 = 53L;
  static const jint D6 = 54L;
  static const jint D7 = 55L;
  static const jint D8 = 56L;
  static const jint D9 = 57L;
  static const jint A = 65L;
  static const jint B = 66L;
  static const jint C = 67L;
  static const jint D = 68L;
  static const jint E = 69L;
  static const jint F = 70L;
  static const jint G = 71L;
  static const jint H = 72L;
  static const jint I = 73L;
  static const jint J = 74L;
  static const jint K = 75L;
  static const jint L = 76L;
  static const jint M = 77L;
  static const jint N = 78L;
  static const jint O = 79L;
  static const jint P = 80L;
  static const jint Q = 81L;
  static const jint R = 82L;
  static const jint S = 83L;
  static const jint T = 84L;
  static const jint U = 85L;
  static const jint V = 86L;
  static const jint W = 87L;
  static const jint X = 88L;
  static const jint Y = 89L;
  static const jint Z = 90L;
  static const jint LWin = 91L;
  static const jint RWin = 92L;
  static const jint Apps = 93L;
  static const jint NumPad0 = 96L;
  static const jint NumPad1 = 97L;
  static const jint NumPad2 = 98L;
  static const jint NumPad3 = 99L;
  static const jint NumPad4 = 100L;
  static const jint NumPad5 = 101L;
  static const jint NumPad6 = 102L;
  static const jint NumPad7 = 103L;
  static const jint NumPad8 = 104L;
  static const jint NumPad9 = 105L;
  static const jint Multiply = 106L;
  static const jint Add = 107L;
  static const jint Separator = 108L;
  static const jint Subtract = 109L;
  static const jint Decimal = 110L;
  static const jint Divide = 111L;
  static const jint F1 = 112L;
  static const jint F2 = 113L;
  static const jint F3 = 114L;
  static const jint F4 = 115L;
  static const jint F5 = 116L;
  static const jint F6 = 117L;
  static const jint F7 = 118L;
  static const jint F8 = 119L;
  static const jint F9 = 120L;
  static const jint F10 = 121L;
  static const jint F11 = 122L;
  static const jint F12 = 123L;
  static const jint NumLock = 144L;
  static const jint Scroll = 145L;
  static const jint LShiftKey = 160L;
  static const jint RShiftKey = 161L;
  static const jint LControlKey = 162L;
  static const jint RControlKey = 163L;
  static const jint LMenu = 164L;
  static const jint RMenu = 165L;
  static const jint OemSemicolon = 186L;
  static const jint Oemplus = 187L;
  static const jint Oemcomma = 188L;
  static const jint OemMinus = 189L;
  static const jint OemPeriod = 190L;
  static const jint OemQuestion = 191L;
  static const jint Oemtilde = 192L;
  static const jint OemOpenBrackets = 219L;
  static const jint OemPipe = 220L;
  static const jint OemCloseBrackets = 221L;
  static const jint OemQuotes = 222L;
  static const jint OemBackslash = 226L;
private:
  jintArray __attribute__((aligned(__alignof__( ::java::lang::Object ))))  mapUS102;
  jintArray mapUS102E0;
  jintArray mapJP109;
  jintArray mapJP109E0;
  jcharArray keyTopMapUS102;
  jcharArray keyTopMapUS102S;
  jcharArray keyTopMapJP109;
  jcharArray keyTopMapJP109S;
public:

  static ::java::lang::Class class$;
};

#endif /* __org_monaos_Keys__ */
