// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __org_monaos_MessageInfo__
#define __org_monaos_MessageInfo__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace org
  {
    namespace monaos
    {
      class MessageInfo;
    }
  }
}

class org::monaos::MessageInfo : public ::java::lang::Object
{
public:
  MessageInfo ();
  jint __attribute__((aligned(__alignof__( ::java::lang::Object ))))  header;
  jint arg1;
  jint arg2;
  jint arg3;
  jint from;

  static ::java::lang::Class class$;
};

#endif /* __org_monaos_MessageInfo__ */
