// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __org_monaos_Screen__
#define __org_monaos_Screen__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace org
  {
    namespace monaos
    {
      class Screen;
    }
  }
}

class org::monaos::Screen : public ::java::lang::Object
{
public:
  static jint getWidth ();
  static jint getHeight ();
  static jint getBpp ();
  Screen ();

  static ::java::lang::Class class$;
};

#endif /* __org_monaos_Screen__ */
