#ifndef __PRIMITIVE_PROCEDURE_STRING_PROCEDURES_H__
#define __PRIMITIVE_PROCEDURE_STRING_PROCEDURES_H__

PROCEDURE(StringEqualP, "string=?")
{
    ARGC_SHOULD_BE(2);
    CAST(ARGV(0), String, s);
    RETURN_BOOLEAN(s->equal(ARGV(1)));
}

#endif // __PRIMITIVE_PROCEDURE_STRING_PROCEDURES_H__
