TARGET  = PROCESS
SOURCES = main.cpp ProcessManager.cpp ProcessInfo.cpp
INSTDIR = $(BINDIR)/root/SERVERS

MONADIR    = ../../..
ADDLINK    = -lmonalibc
ADDLINKDEP = $(MONADIR)/lib/libmonalibc.a
include $(MONADIR)/env/monapi-bin.inc

include dependencies
