ONIG_DIR = ./onig/onig-5.7.0

ONIG_SOURCES = \
	onig/onig-5.7.0/regcomp.c \
	onig/onig-5.7.0/regenc.c \
	onig/onig-5.7.0/regerror.c \
	onig/onig-5.7.0/regexec.c \
	onig/onig-5.7.0/regext.c \
	onig/onig-5.7.0/reggnu.c \
	onig/onig-5.7.0/regparse.c \
	onig/onig-5.7.0/regposerr.c \
	onig/onig-5.7.0/regposix.c \
	onig/onig-5.7.0/regsyntax.c \
	onig/onig-5.7.0/regtrav.c \
	onig/onig-5.7.0/regversion.c \
	onig/onig-5.7.0/st.c \
	onig/onig-5.7.0/enc/ascii.c \
	onig/onig-5.7.0/enc/big5.c \
	onig/onig-5.7.0/enc/cp1251.c \
	onig/onig-5.7.0/enc/euc_jp.c \
	onig/onig-5.7.0/enc/euc_kr.c \
	onig/onig-5.7.0/enc/euc_tw.c \
	onig/onig-5.7.0/enc/gb18030.c \
	onig/onig-5.7.0/enc/iso8859_1.c \
	onig/onig-5.7.0/enc/iso8859_10.c \
	onig/onig-5.7.0/enc/iso8859_11.c \
	onig/onig-5.7.0/enc/iso8859_13.c \
	onig/onig-5.7.0/enc/iso8859_14.c \
	onig/onig-5.7.0/enc/iso8859_15.c \
	onig/onig-5.7.0/enc/iso8859_16.c \
	onig/onig-5.7.0/enc/iso8859_2.c \
	onig/onig-5.7.0/enc/iso8859_3.c \
	onig/onig-5.7.0/enc/iso8859_4.c \
	onig/onig-5.7.0/enc/iso8859_5.c \
	onig/onig-5.7.0/enc/iso8859_6.c \
	onig/onig-5.7.0/enc/iso8859_7.c \
	onig/onig-5.7.0/enc/iso8859_8.c \
	onig/onig-5.7.0/enc/iso8859_9.c \
	onig/onig-5.7.0/enc/sjis.c \
	onig/onig-5.7.0/enc/unicode.c \
	onig/onig-5.7.0/enc/utf16_be.c \
	onig/onig-5.7.0/enc/utf16_le.c \
	onig/onig-5.7.0/enc/utf32_be.c \
	onig/onig-5.7.0/enc/utf32_le.c \
	onig/onig-5.7.0/enc/utf8.c
