all:
	@cd non-gui && $(MAKE) $@
	@cd gui && $(MAKE) $@
	@cd baygui && $(MAKE) $@

install:
	@cd non-gui && $(MAKE) $@
	@cd gui && $(MAKE) $@
	@cd baygui && $(MAKE) $@

clean:
	@cd non-gui && $(MAKE) $@
	@cd gui && $(MAKE) $@
	@cd baygui && $(MAKE) $@

depend:
	@cd non-gui && $(MAKE) $@
	@cd gui && $(MAKE) $@
	@cd baygui && $(MAKE) $@

distclean:
	@cd non-gui && $(MAKE) $@
	@cd gui && $(MAKE) $@
	@cd baygui && $(MAKE) $@
