SRCTOP=../..
include $(SRCTOP)/Makefile.inc

TARGET  = SCHEME
include Makefile.src.inc
INSTDIR = $(BINDIR)/SERVERS

ADDINCLUDE = -I $(MONADIR)/include/monalibc -I .
ADDLINK    = -lmonalibc
ADDLINKDEP = $(MONADIR)/lib/libmonalibc.a
SHAREDIR   = $(MONADIR)/share

ifneq ($(BUILD_TARGET),ELF)
include $(SHAREDIR)/configs/monapi-ex5.inc
else
include $(SHAREDIR)/configs/monapi-el5.inc
endif

-include dependencies
