// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __Vector__
#define __Vector__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  class Vector;
}

class Vector : public ::java::lang::Object
{
public: // actually package-private
  Vector ();
  Vector (jfloat, jfloat, jfloat);
  virtual void Initialize (::Vector *);
  virtual void Add (::Vector *);
  virtual jfloat Length ();
  virtual void Normalize ();
  virtual jfloat DotProduct (::Vector *);
  virtual void CrossProduct (::Vector *, ::Vector *);
  virtual void Invert ();
  jfloat __attribute__((aligned(__alignof__( ::java::lang::Object ))))  x;
  jfloat y;
  jfloat z;
public:

  static ::java::lang::Class class$;
};

#endif /* __Vector__ */
