all:
	@cd jhello && $(MAKE) $@
	@cd jnoiz2bg && $(MAKE) $@
	@cd java3d01 && $(MAKE) $@
	@cd java3d02 && $(MAKE) $@
	@cd java3d03 && $(MAKE) $@
	@cd java3d04 && $(MAKE) $@
	@cd java3d13 && $(MAKE) $@

install:
	@cd jhello && $(MAKE) $@
	@cd jnoiz2bg && $(MAKE) $@
	@cd java3d01 && $(MAKE) $@
	@cd java3d02 && $(MAKE) $@
	@cd java3d03 && $(MAKE) $@
	@cd java3d04 && $(MAKE) $@
	@cd java3d05 && $(MAKE) $@
	@cd java3d06 && $(MAKE) $@
	@cd java3d07 && $(MAKE) $@
	@cd java3d08 && $(MAKE) $@
	@cd java3d09 && $(MAKE) $@
	@cd java3d10 && $(MAKE) $@
	@cd java3d11 && $(MAKE) $@
	@cd java3d12 && $(MAKE) $@
	@cd java3d13 && $(MAKE) $@
	@cd java3d16 && $(MAKE) $@
	@cd java3d18 && $(MAKE) $@
	@cd java3d19 && $(MAKE) $@

clean: touchdepend
	@cd jhello && $(MAKE) $@
	@cd jnoiz2bg && $(MAKE) $@
	@cd java3d01 && $(MAKE) $@
	@cd java3d02 && $(MAKE) $@
	@cd java3d03 && $(MAKE) $@
	@cd java3d04 && $(MAKE) $@
	@cd java3d05 && $(MAKE) $@
	@cd java3d06 && $(MAKE) $@
	@cd java3d07 && $(MAKE) $@
	@cd java3d08 && $(MAKE) $@
	@cd java3d09 && $(MAKE) $@
	@cd java3d10 && $(MAKE) $@
	@cd java3d11 && $(MAKE) $@
	@cd java3d12 && $(MAKE) $@
	@cd java3d13 && $(MAKE) $@
	@cd java3d16 && $(MAKE) $@
	@cd java3d18 && $(MAKE) $@
	@cd java3d19 && $(MAKE) $@

depend: touchdepend
	@cd jhello && $(MAKE) $@
	@cd jnoiz2bg && $(MAKE) $@
	@cd java3d01 && $(MAKE) $@
	@cd java3d02 && $(MAKE) $@
	@cd java3d03 && $(MAKE) $@
	@cd java3d04 && $(MAKE) $@
	@cd java3d05 && $(MAKE) $@
	@cd java3d06 && $(MAKE) $@
	@cd java3d07 && $(MAKE) $@
	@cd java3d08 && $(MAKE) $@
	@cd java3d09 && $(MAKE) $@
	@cd java3d10 && $(MAKE) $@
	@cd java3d11 && $(MAKE) $@
	@cd java3d12 && $(MAKE) $@
	@cd java3d13 && $(MAKE) $@
	@cd java3d16 && $(MAKE) $@
	@cd java3d18 && $(MAKE) $@
	@cd java3d19 && $(MAKE) $@

distclean:
	rm -f jhello/dependencies
	rm -f jnoiz2bg/dependencies
	rm -f java3d01/dependencies
	rm -f java3d02/dependencies
	rm -f java3d03/dependencies
	rm -f java3d04/dependencies
	rm -f java3d05/dependencies
	rm -f java3d06/dependencies
	rm -f java3d07/dependencies
	rm -f java3d08/dependencies
	rm -f java3d09/dependencies
	rm -f java3d10/dependencies
	rm -f java3d11/dependencies
	rm -f java3d12/dependencies
	rm -f java3d13/dependencies
	rm -f java3d16/dependencies
	rm -f java3d18/dependencies
	rm -f java3d19/dependencies

touchdepend:
	touch jhello/dependencies
	touch jnoiz2bg/dependencies
	touch java3d01/dependencies
	touch java3d02/dependencies
	touch java3d03/dependencies
	touch java3d04/dependencies
	touch java3d05/dependencies
	touch java3d06/dependencies
	touch java3d07/dependencies
	touch java3d08/dependencies
	touch java3d09/dependencies
	touch java3d10/dependencies
	touch java3d11/dependencies
	touch java3d12/dependencies
	touch java3d13/dependencies
	touch java3d16/dependencies
	touch java3d18/dependencies
	touch java3d19/dependencies
