all:
	@cd reversi && $(MAKE) $@
	@cd ps && $(MAKE) $@
	@cd 2chAA && $(MAKE) $@
	@cd noiz2bg && $(MAKE) $@
	@cd fire && $(MAKE) $@
#	@cd launcher && $(MAKE) $@
	@cd shell && $(MAKE) $@
	@cd clock && $(MAKE) $@
	@cd cube && $(MAKE) $@
	@cd kukuri && $(MAKE) $@
	@cd mtorz && $(MAKE) $@
	@cd monafile && $(MAKE) $@
	@cd hige3D && $(MAKE) $@

install:
	@cd reversi && $(MAKE) $@
	@cd ps && $(MAKE) $@
	@cd 2chAA && $(MAKE) $@
	@cd noiz2bg && $(MAKE) $@
	@cd fire && $(MAKE) $@
#	@cd launcher && $(MAKE) $@
	@cd shell && $(MAKE) $@
	@cd clock && $(MAKE) $@
	@cd cube && $(MAKE) $@
	@cd kukuri && $(MAKE) $@
	@cd mtorz && $(MAKE) $@
	@cd monafile && $(MAKE) $@
	@cd hige3D && $(MAKE) $@

clean: touchdepend
	@cd reversi && $(MAKE) $@
	@cd ps && $(MAKE) $@
	@cd 2chAA && $(MAKE) $@
	@cd noiz2bg && $(MAKE) $@
	@cd fire && $(MAKE) $@
#	@cd launcher && $(MAKE) $@
	@cd shell && $(MAKE) $@
	@cd clock && $(MAKE) $@
	@cd cube && $(MAKE) $@
	@cd kukuri && $(MAKE) $@
	@cd mtorz && $(MAKE) $@
	@cd monafile && $(MAKE) $@
	@cd hige3D && $(MAKE) $@

depend: touchdepend
	@cd reversi && $(MAKE) $@
	@cd ps && $(MAKE) $@
	@cd 2chAA && $(MAKE) $@
	@cd noiz2bg && $(MAKE) $@
	@cd fire && $(MAKE) $@
#	@cd launcher && $(MAKE) $@
	@cd shell && $(MAKE) $@
	@cd clock && $(MAKE) $@
	@cd cube && $(MAKE) $@
	@cd kukuri && $(MAKE) $@
	@cd mtorz && $(MAKE) $@
	@cd monafile && $(MAKE) $@
	@cd hige3D && $(MAKE) $@

distclean:
	rm -f reversi/dependencies
	rm -f ps/dependencies
	rm -f 2chAA/dependencies
	rm -f noiz2bg/dependencies
	rm -f fire/dependencies
#	rm -f launcher/dependencies
	rm -f shell/dependencies
	rm -f clock/dependencies
	rm -f cube/dependencies
	rm -f kukuri/dependencies
	rm -f mtorz/dependencies
	rm -f monafile/dependencies
	rm -f hige3D/dependencies

touchdepend:
	touch reversi/dependencies
	touch ps/dependencies
	touch 2chAA/dependencies
	touch noiz2bg/dependencies
	touch fire/dependencies
#	touch launcher/dependencies
	touch shell/dependencies
	touch clock/dependencies
	touch cube/dependencies
	touch kukuri/dependencies
	touch mtorz/dependencies
	touch monafile/dependencies
	touch hige3D/dependencies
