all:
	@cd reversi; $(MAKE) $@
	@cd ps; $(MAKE) $@
	@cd 2chAA; $(MAKE) $@
	@cd noiz2bg; $(MAKE) $@

install:
	@cd reversi; $(MAKE) $@
	@cd ps; $(MAKE) $@
	@cd 2chAA; $(MAKE) $@
	@cd noiz2bg; $(MAKE) $@

clean:
	@cd reversi; $(MAKE) $@
	@cd ps; $(MAKE) $@
	@cd 2chAA; $(MAKE) $@
	@cd noiz2bg; $(MAKE) $@

depend:
	@cd reversi; $(MAKE) $@
	@cd ps; $(MAKE) $@
	@cd 2chAA; $(MAKE) $@
	@cd noiz2bg; $(MAKE) $@
