#ifndef _SERVERS_MOUSE_
#define _SERVERS_MOUSE_

enum
{
    MSG_MOUSE_INFO = 0x302,
    MSG_MOUSE_ENABLE_CURSOR,
    MSG_MOUSE_DISABLE_CURSOR,
    MSG_MOUSE_GET_CURSOR_POSITION,
    MSG_MOUSE_SET_CURSOR_POSITION,
    MSG_MOUSE_PRESS,
    MSG_MOUSE_RELEASE
};

#endif
