#ifndef _SERVER_MOUSE_
#define _SERVER_MOUSE_

enum
{
    MSG_MOUSE_REGIST_TO_SERVER = 0x0300,
    MSG_MOUSE_UNREGIST_FROM_SERVER,
    MSG_MOUSE_INFO,
    MSG_MOUSE_ENABLE_CURSOR,
    MSG_MOUSE_DISABLE_CURSOR,
    MSG_MOUSE_GET_CURSOR_POSITION,
};

#endif;_
