#ifndef _SERVER_PROCESS_
#define _SERVER_PROCESS_

enum
{
    MSG_PROCESS_EXECUTE_FILE = 0x0500,
    MSG_PROCESS_CREATE_IMAGE,
    MSG_PROCESS_GET_PROCESS_INFO = 0x1000,
    MSG_PROCESS_CREATED,
    MSG_PROCESS_TERMINATED,
    MSG_PROCESS_GET_COMMON_PARAMS,
    MSG_PROCESS_GET_PROCESS_STDIO,
};

#endif
