#ifndef _SERVERS_SERVERS_
#define _SERVERS_SERVERS_

enum
{
    MSG_DISPOSE_HANDLE          = 0x0100,

    MSG_REGISTER_TO_SERVER      = 0x0110,
    MSG_STOP_SERVER,
    MSG_UNREGISTER_FROM_SERVER,
    MSG_GET_OUT_STREAM_HANDLE = 0x0120,
    MSG_CHANGE_OUT_STREAM_BY_HANDLE,
};

#endif
