/*
Copyright (c) 2004 bayside
All rights reserved.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __RESOURCES_H__
#define __RESOURCES_H__

#define WINDOWMANAGER_MENU_TITLE_JP "ファイル　編集　表示　特別　ヘルプ"
#define WINDOWMANAGER_MENU_TITLE_EN "File Edit View Special Help"

#define APP_NAME			"GLAUNCH.EX5"
#define FILE_NAME			"FILE"
#define TERMINAL_NAME		"TERMINAL"
#define TRASHBOX_NAME		"TRASHBOX"
#define BITMAP_NAME			"BITMAP"
#define TEXT_NAME			"TEXT"

#define FILE_TITLE			"Mona FDD"
#define TERMINAL_TITLE		"た～みなる"
#define TRASHBOX_TITLE		"ゴミ箱"

#define FILE_FULLNAME		"/APPS/BAYGUI/GLAUNCH.EX5 FILE"
#define TERMINAL_FULLNAME	"/APPS/BAYGUI/GSHELL.EX5"
#define TRASHBOX_FULLNAME	"/APPS/BAYGUI/GLAUNCH.EX5 TRASHBOX"
#define BITMAP_FULLNAME		"/APPS/BAYGUI/GLAUNCH.EX5 BITMAP "
#define TEXT_FULLNAME		"/APPS/BAYGUI/GLAUNCH.EX5 TEXT "

#define ARRANGE_WIDTH  80
#define ARRANGE_HEIGHT 64

/** アイコンの種類 */
enum
{
	iconsArchive,
	iconsExecutable,
	iconsFile,
	iconsFloppy,
	iconsFolder,
	iconsTrashbox,
	iconsPicture,
	iconsServer,
	iconsTerminal,
	iconsText
};

#endif // __RESOURCES_H__
