// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __Texture__
#define __Texture__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  class Texture;
}

class Texture : public ::java::lang::Object
{
public:
  Texture ();
  jint __attribute__((aligned(__alignof__( ::java::lang::Object ))))  width;
  jint height;
  jintArray data;

  static ::java::lang::Class class$;
};

#endif /* __Texture__ */
