/*
Copyright (c) 2004 bayside
All rights reserved.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __GSHELL_H__
#define __GSHELL_H__

#define TERMINAL_WIDTH	60
#define TERMINAL_HEIGHT	20
#define TERMINAL_PROMPT	"MONA>"

/** 端末エミュレータ */
class GShell : public Window
{
private:
	int cursor, rows, cols;
	char buffer[TERMINAL_WIDTH * TERMINAL_HEIGHT];
	
public:
	GShell();
	
	virtual ~GShell() {}
	
	/** バッファーをクリアする */
	void clear();
	
	/** 文字列を挿入する */
	void insert(const char *text);
	
	/** イベントハンドラ */
	virtual void onEvent(Event *e);
	
	/** 描画ハンドラ */
	virtual void onPaint(_P<Graphics> g);
};

#endif  // __GSHELL_H__
