// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_lang_String__
#define __java_lang_String__

#pragma interface

#include <java/lang/Object.h>

class java::lang::String : public ::java::lang::Object
{
public:
  String ();
  virtual ::java::lang::String *toString () { return this; }
  jint length () { return count; }
  ::java::lang::Object * __attribute__((aligned(__alignof__( ::java::lang::Object )))) data;
  jint boffset;
  jint count;

  static ::java::lang::Class class$;
};

#endif /* __java_lang_String__ */
