// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_lang_String__
#define __java_lang_String__

#pragma interface

#include <java/lang/Object.h>

class java::lang::String : public ::java::lang::Object
{
};

#endif /* __java_lang_String__ */
