// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_lang_StringBuffer__
#define __java_lang_StringBuffer__

#pragma interface

#include <java/lang/Object.h>

class java::lang::StringBuffer : public ::java::lang::Object
{
public:
  virtual ::java::lang::StringBuffer *append (jint);
  virtual ::java::lang::StringBuffer *append (::java::lang::Object *);
  virtual ::java::lang::StringBuffer *append (::java::lang::String *);
  StringBuffer ();

  static ::java::lang::Class class$;
};

#endif /* __java_lang_StringBuffer__ */
