// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_lang_System__
#define __java_lang_System__

#pragma interface

#include <java/lang/Object.h>

class java::lang::System : public ::java::lang::Object
{
public:
  System ();
  static ::java::io::PrintStream *out;

  static ::java::lang::Class class$;
};

#endif /* __java_lang_System__ */
